version: '3.8'

services:
  helloworld:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        APP_DIR: helloworld
    command: ./app
    volumes:
      - ../helloworld:/app/helloworld

  api-practice:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        APP_DIR: api-practice
    command: ./app
    volumes:
      - ../api-practice:/app/api-practice
    ports:
      - "8080:8080"

  concurrency-practice:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        APP_DIR: concurrency-practice
    command: ./app
    volumes:
      - ../concurrency-practice:/app/concurrency-practice
    ports:
      - "8081:8081"

  array:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        APP_DIR: array
    command: ./app
    volumes:
      - ../array:/app/array
    ports:
      - "8082:8082"

  crud-files:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        APP_DIR: crud-files
    command: ./app
    volumes:
      - ../crud-files:/app/crud-files
      - ../data:/app/data
    ports:
      - "8083:8083"

  aa:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        APP_DIR: aa
    command: ./app

    # 他のサービスを追加する場合は以下のように追加
    # other-app:
    #   build:
    #     context: ..
    #     dockerfile: docker/Dockerfile
    #     args:
    #       APP_DIR: other-app
    #   command: ./app
    #   volumes:
    #     - ../other-app:/app/other-app