version: '3.8'

services:
  learning-web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../learning-web:/app/learning-web
    environment:
      - APP_DIR=learning-web
    ports:
      - "8080:8080"
    # TODO: 以下のサービスは必要に応じて追加してください
    # depends_on:
    #   - db
    #   - redis

  # TODO: データベースの設定
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: learning_web
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  # TODO: Redisの設定
  # redis:
  #   image: redis:7
  #   ports:
  #     - "6379:6379"

# volumes:
#   postgres_data: 